# Obsidian glass palette
background = #0d0d0d
foreground = #f2f2f2
cursor-color = #f2f2f2
selection-background = #2a2a2a
selection-foreground = #ffffff

background-opacity = 0.88
background-blur = true

window-padding-x = 22
window-padding-y = 22
window-decoration = false

palette = 0=#121212
palette = 1=#a67a7a
palette = 2=#87967d
palette = 3=#a89673
palette = 4=#7d8a96
palette = 5=#95829a
palette = 6=#7d9693
palette = 7=#d0d0d0
palette = 8=#4a4a4a
palette = 9=#b88a8a
palette = 10=#93a389
palette = 11=#b8a27f
palette = 12=#8c99a6
palette = 13=#a18ea6
palette = 14=#89a3a0
palette = 15=#ffffff
