# Tokyo Night Neon Colors
$blue_neon   = rgba(ffffffff)
#$purple_neon = rgba(bb9af7ff)
$inactive    = rgba(41486866) # Faint gray for inactive windows

general {
    gaps_in = 2
    gaps_out = 4
    border_size = 1            # Clean, thin 1px border
    
    # Sharp gradient for the active window
    col.active_border = $blue_neon # $purple_neon 45deg
    col.inactive_border = $inactive

    layout = dwindle
}

decoration {
    rounding = 10                  # Slightly tighter corners for thin borders
    
    active_opacity = 0.95          # Clearer readability
    inactive_opacity = 0.90
    
    blur {
        enabled = true
        size = 4                   # Tighter blur
        passes = 3
        ignore_opacity = true
        new_optimizations = true
    }

    shadow {
        enabled = true
        range = 15
        render_power = 3
        color = rgba(1a1b2666)
    }
}

animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    
    animation = windows, 1, 4, myBezier
    animation = windowsOut, 1, 4, default, popin 80%
    animation = border, 1, 5, default
    animation = fade, 1, 4, default
    animation = workspaces, 1, 4, default, slide
}

layerrule = blur on, match:namespace walker
layerrule = ignore_alpha 0, match:namespace walker

layerrule = blur on, match:namespace notifications
layerrule = ignore_alpha 0, match:namespace notifications

layerrule = blur on, match:namespace swayosd
layerrule = ignore_alpha 0, match:namespace swayosd
