# Obsidian glass palette
foreground #f2f2f2
background #0d0d0d
selection_foreground #ffffff
selection_background #2a2a2a

cursor #f2f2f2
cursor_text_color #000000

active_border_color #8c8c8c
inactive_border_color #1a1a1a

background_opacity 0.75
dynamic_background_opacity yes

window_padding_width 20

tab_bar_margin_width      10
tab_bar_margin_height     10 0
tab_bar_style             separator
tab_separator             ""
active_tab_font_style     bold
active_tab_foreground     #ffffff
active_tab_background     #333333
inactive_tab_foreground   #666666
inactive_tab_background   #151515

color0 #121212
color1 #a67a7a
color2 #87967d
color3 #a89673
color4 #7d8a96
color5 #95829a
color6 #7d9693
color7 #d0d0d0
color8 #4a4a4a
color9 #b88a8a
color10 #93a389
color11 #b8a27f
color12 #8c99a6
color13 #a18ea6
color14 #89a3a0
color15 #ffffff

font_family      JetBrainsMono Nerd Font
font_size        14.0
