background       = "#0d0d0d"
background-alpha = 0.72
text             = "#f2f2f2"
placeholder      = "#a0a0a0"
text-error       = "#a67a7a"
border-active    = "#f2f2f2"
border-error     = "#a67a7a"
border-alpha     = 0.32
selection        = "#8c8c8c"
selection-alpha  = 0.45
